### ISSUE TITLE
Dataset news su guerra in Ucraina

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#126]
<pre><yamldata>
title: Dataset news su guerra in Ucraina
description: 'Utilizza algoritmo che estrae e analizza da una serie di testate tutti
  gli articoli che parlano della guerra in Ucraina.

  Il risultato è un''enorme dataset che consente di raccontare l''invasione nel suo
  insieme'
link: https://bit.ly/3J659kj
location:
  mode: autocomplete
  address: {}
label: news
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente vedi #
