### ISSUE TITLE
Errore Link UniCal

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#183]
<pre><yamldata>
title: Errore Link UniCal
description: 'ciao al link UniCal, su Cosenza, con offerta 15 borse di studio universitarie
  il link segnala error page

  https://www.unical.it/portale/portaltemplates/view/view.cfm?116448'
link: ''
location:
  mode: autocomplete
  address: {}
label: document_data
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Link corretto. Chiudo.
