### ISSUE TITLE
Terres Des Hommes Italia cerca mediatori linguistici in ucraino a Milano, Monza e Brianza e Udine

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#191]
<pre><yamldata>
type: jobOffer
offerFromWho: Terres Des Hommes Italia
title: Ricerca mediatori culturali a Milano, Monza e Brianza e Udine
recipients: ''
description: 'L''organizzazione Terres Des Hommes cerca per i propri servizi di accoglienza,
  sportello e inclusione cerca mediatori e mediatrici in lingua ucraina.

  I servizi saranno attivi nelle città di Milano e dintorni, Monza e Brianza, Udine
  e Trieste. Si richiede la residenza e il domicilio nelle zone di attività.

  Inviare curriculum vitae a: ucraina@tdhitaly.org

  È richiesta disponibilità immediata per impiego part-time di almeno 19 ore settimanali.

  Scadenza vacancy: 15 aprile 2022'
url: https://terredeshommes.it/chi-siamo/lavora-con-noi/?fbclid=IwAR11P_lEbSb3L14R-tO4xFbr1Crn9FBBZ6--1KlGASfAzs-jVYqx7P-pa8g
address:
  mode: autocomplete
  address:
    place_id: 286263950
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: node
    osm_id: 62505581
    boundingbox:
    - '45.3041943'
    - '45.6241943'
    - '9.0296346'
    - '9.3496346'
    lat: '45.4641943'
    lon: '9.1896346'
    display_name: Milano, Milan, Milano, Lombardia, 20122, Italia
    class: place
    type: city
    importance: 0.8390652078701348
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_place_city.p.20.png
    address:
      city: Milano
      county: Milano
      state: Lombardia
      postcode: '20122'
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by Patriziacar** [comment]
credo andrebbe etichettata anche come Job

**Comment by cristigalas** [comment]
@Patriziacar giusto perché cercano mediatori in ucraino. E poi help perché è una richiesta di aiuto. Tutte le richieste vanno in Help. E poi aggiungiamo anche label traduzioni. E Millestone 16 aprile, così il giorno dopo la scadenza chiudiamo la segnalazione perché scaduta.

**Comment by cristigalas** [comment]
Scaduta, chiudo.
