### ISSUE TITLE
A Milano e comuni limitrofi mamma con due bambini fuggita dall'Ucraina cerca alloggio economico

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#199]
<pre><yamldata>
nameSurname: Hanna pozniak
phoneNumber: '+393287425807'
email: gaigan@gmail.com
title: Search for house
recipients: ''
description: Buongiorno, mi chiamo Gaia Gandini e sto ospitando la famiglia Pozniak,
  mamma con figli di 16 e 9 anni a casa mia, ma riesco fino al 1/4/22. Cercano a Milano e comuni limitrofi alloggio gratuito o molto economico per successivo periodo. Non parlano inglese solo ucraino
  per questo scrivo io. Grazie!
url: ''
location:
  mode: autocomplete
  address:
    place_id: 283684439
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 44915
    boundingbox:
    - '45.3867381'
    - '45.5358482'
    - '9.0408867'
    - '9.2781103'
    lat: '45.4612939'
    lon: '9.172356290785304'
    display_name: Milan, Milano, Lombardia, Italia
    class: boundary
    type: administrative
    importance: 0.8490652078701348
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      city: Milan
      county: Milano
      state: Lombardia
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
label: help
submit: true
Posizione: 45.4612939 9.172356290785304
</yamldata></pre>

**Comment by cristigalas** [comment]
La signora ha trovato un nuovo alloggio a Bussero. Chiudo.
