### ISSUE TITLE
Prato 19 marzo, concerto Coro Maggio Fiorentino a sostegno della raccolta fondi per l’Ucraina di Croce Rossa

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#202]
<pre><yamldata>
title: Artisti Maggio Fiorentino e Croce Rossa italiana
description: 'concerto beneficio per l''Ucraina in programma sabato 19 marzo, alle
  21, al Politeama pratese. L''iniziativa è organizzata da un gruppo di artisti lirici
  professionisti del coro del Maggio musicale fiorentino, tra i quali molti pratesi
  e molti vincitori di concorsi nazionali e internazionali. Ad unire il gruppo è il
  desiderio di dare un contributo alla macchina della solidarietà che sta aiutando
  la popolazione ucraina. Il concerto è strutturato su una scaletta di opere dell''Ottocento
  di compositori tra i più celebri.

  Il ricavato della serata sarà devoluto al sostegno dell''Ucraina e ogni spettatore
  potrà contribuire con una donazione diretta partecipando al concerto oppure attraverso
  un bonifico intestato all''Associazione Croce Rossa italiana'
heading: Associazione Croce Rossa italiana
iban: IT93H0200803284000105889169
bicSwift: Unicritmirnp
ccPostal: ''
causal: causale Emergenza Ucraina
link: http://www.notiziediprato.it/news/gli-artisti-del-maggio-musicale-fiorentino-al-politeama-per-un-concerto-benefico-pro-emergenza-ucraina
email: ''
location:
  mode: autocomplete
  address:
    place_id: 179411580
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: way
    osm_id: 324533597
    boundingbox:
    - '43.8812436'
    - '43.8816433'
    - '11.0992461'
    - '11.0998252'
    lat: '43.88142935'
    lon: '11.09951159358597'
    display_name: Politeama, 33, Via Giuseppe Garibaldi, il Cantiere, Prato, Toscana,
      59100, Italia
    class: amenity
    type: theatre
    importance: 0.2808812954247281
    icon: https://nominatim.openstreetmap.org/ui/mapicons//tourist_theatre.p.20.png
    address:
      amenity: Politeama
      house_number: '33'
      road: Via Giuseppe Garibaldi
      neighbourhood: il Cantiere
      city: Prato
      county: Prato
      state: Toscana
      postcode: '59100'
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
label: fundraising
submit: true
Posizione: 43.88142935 11.09951159358597
</yamldata></pre>

**Comment by cristigalas** [comment]
Conclusa. Chiudo.
