### ISSUE TITLE
Anna è nata a Martinafranca

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#206]
<pre><yamldata>
title: Anna è nata a Martinafranca
description: 'Anna è nata a #MartinaFranca, pesa 3kg e sta bene.

  Nastya, sua madre, ha affrontato il viaggio dall'' #Ucraina al nono mese di gravidanza.'
link: https://twitter.com/RegionePuglia/status/1504507015133073414
location:
  mode: manual
  address:
    address1: ''
    address2: ''
    city: MartinaFranca
    state: ''
    country: ''
    zip: '74015'
label: news
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Non pertinente. Non accetto e chiudo.
