### ISSUE TITLE
MILANO AIUTA UCRAINA: istruzioni per le donazioni alimentari

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#223]
<pre><yamldata>
type: materialGoods
offerFromWho: Comune di Milano
title: 'MILANO AIUTA UCRAINA: istruzioni per le donazioni alimentari'
recipients: ''
description: 'Grazie al coordinamento con Prefettura, Questura, Istituzioni e associazioni
  del terzo settore, il Comune di Milano sta mettendo in campo una serie di azioni
  per accogliere al meglio i profughi ucraini in arrivo in città.

  Per coloro che sono in arrivo in stazione centrale, la Protezione Civile ha attivato
  un Info Point in cui sono fornite le prime indicazioni utili a coloro che hanno
  già un luogo dove andare e a chi invece ha necessità di trovare una sistemazione
  temporanea. Da questa settimana è attivo un canale dedicato all’emergenza al numero
  020202 a cui rispondono operatori che possono fornire informazioni su l’accoglienza,
  le reti di supporto che riguardano alimenti, beni di prima necessità, vestiario
  e orientare chi vuole mettere a disposizione alloggi per le famiglie.'
url: https://foodpolicymilano.org/milano-aiuta-ucraina/
address:
  mode: autocomplete
  address:
    place_id: 286263950
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: node
    osm_id: 62505581
    boundingbox:
    - '45.3041943'
    - '45.6241943'
    - '9.0296346'
    - '9.3496346'
    lat: '45.4641943'
    lon: '9.1896346'
    display_name: Milano, Milan, Milano, Lombardia, 20122, Italia
    class: place
    type: city
    importance: 0.8490652078701348
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_place_city.p.20.png
    address:
      city: Milano
      county: Milano
      state: Lombardia
      postcode: '20122'
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
