### ISSUE TITLE
Ucraina: dalla protezione civile dell'Alto Adige e Trentino materiale per Moldavia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#236]
<pre><yamldata>
title: 'Ucraina: dalla protezione civile dell''Alto Adige e Trentino materiale per
  Moldavia'
description: La provincie di Trento e Bolzano forniscono una tendopoli da 500 persone
  da installare nelle vicinanze della capitale moldava Chișinău.
link: https://www.ansa.it/trentino/notizie/2022/03/18/ucraina-da-prot.civile-alto-adige-materiale-per-moldavia_050bf2f5-0394-45bd-927e-a7b3d6e463fd.html
location:
  mode: autocomplete
  address:
    place_id: 331927630
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 1748490
    boundingbox:
    - '46.9203494'
    - '47.0796459'
    - '28.7451209'
    - '28.9720397'
    lat: '47.0245117'
    lon: '28.8322923'
    display_name: Chișinău, Chișinău Municipality, Moldavia
    class: boundary
    type: administrative
    importance: 0.7186443916731856
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      city: Chișinău
      municipality: Chișinău Municipality
      country: Moldavia
      country_code: md
label: news
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
submit: true
Posizione: 47.0245117 28.8322923
</yamldata></pre>

**Comment by cristigalas** [comment]
È una notizia come tante. Non accetto.
