### ISSUE TITLE
Acli Pavia organizza corso gratuito di italiano per profughi ucraini (inizio 5 aprile)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#250]
<pre><yamldata>
type: translation
offerFromWho: Acli Pavia
title: Corso di italiano
recipients: Persone in arrivo dall'Ucraina
description: Acli Pavia - Sezione Provinciale nell'ambito del progetto Legami Solidali,
  organizza un corso gratuito di lingua italiana per i profughi provenienti dall'Ucraina
  a causa dell'emergenza in atto. Il corso si terrà dal 5 aprile al 7 luglio 2022,
  ore 09.00/11.00 in viale Cesare Battisti 142, Pavia
url: https://www.aclipavia.it/corso-italiano-profughi-ucraini/
address:
  mode: autocomplete
  address:
    place_id: 36788835
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: node
    osm_id: 3030681209
    boundingbox:
    - '45.1893437'
    - '45.1894437'
    - '9.1483341'
    - '9.1484341'
    lat: '45.1893937'
    lon: '9.1483841'
    display_name: ACLI Pavia, Viale Cesare Battisti, Ticinello, Pavia, Lombardia,
      27100, Italia
    class: office
    type: association
    importance: 0.611
    address:
      office: ACLI Pavia
      road: Viale Cesare Battisti
      suburb: Ticinello
      city: Pavia
      county: Pavia
      state: Lombardia
      postcode: '27100'
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduto. Chiudo.
