### ISSUE TITLE
Gruppi Telegram per ucraini in Italia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#267]
<pre><yamldata>
title: Canali Telegram per ucraini in Italia
description: 'https://t.me/italia_ucraina_kanal

  https://t.me/dodomu_italia_ucraina

  https://t.me/ucrainiitalia'
link: ''
location:
  mode: autocomplete
  address: {}
label: news
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #253.
