### ISSUE TITLE
Come Tor sta aiutando i russi che vogliono navigare in internet senza censura

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#281]
<pre><yamldata>
title: Come Tor sta aiutando i russi che vogliono navigare in internet senza censura
description: Il progetto di connessioni anonime ha avviato una serie di programmi
  per fornire banda e connettività sicura a chi vive in Ucraina e in Russia
link: https://www.wired.it/article/tor-russia-internet-libero/
location:
  mode: autocomplete
  address:
    place_id: 284261075
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 60189
    boundingbox:
    - '41.1850968'
    - '82.0586232'
    - '-180'
    - '180'
    lat: '64.6863136'
    lon: '97.7453061'
    display_name: Russia
    class: boundary
    type: administrative
    importance: 0.9621923620785889
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      country: Russia
      country_code: ru
label: news
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
submit: true
Posizione: 64.6863136 97.7453061
</yamldata></pre>

**Comment by cristigalas** [comment]
Non pertinente. Non accetto.
