### ISSUE TITLE
Generosità barghigiana per l’Ucraina

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#282]
<pre><yamldata>
title: Generosità barghigiana per l’Ucraina
description: Raccolta di materiale in favore della popolazione ucraina
link: https://www.giornaledibarga.it/2022/03/altra-generosita-barghigiana-per-lucraina-364841/
location:
  mode: autocomplete
  address:
    place_id: 284470068
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 42834
    boundingbox:
    - '44.0366818'
    - '44.1569329'
    - '10.4427967'
    - '10.5833729'
    lat: '44.0739178'
    lon: '10.484263'
    display_name: Barga, Unione dei comuni Media Valle del Serchio, Lucca, Toscana,
      Italia
    class: boundary
    type: administrative
    importance: 0.5566988469684448
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      village: Barga
      municipality: Unione dei comuni Media Valle del Serchio
      county: Lucca
      state: Toscana
      country: Italia
      country_code: it
label: news
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
submit: true
Posizione: 44.0739178 10.484263
</yamldata></pre>

**Comment by cristigalas** [comment]
Nell’articolo si parla di raccolta già avvenuta. Non accetto.
