### ISSUE TITLE
Una piattaforma per trovare accoglienza

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#288]
<pre><yamldata>
type: hospitality
offerFromWho: Piattaforma Eu4ua
title: Una piattaforma per trovare accoglienza
recipients: persone in fuga dall'Ucraina
description: "La piattaforma Eu4ua.org è destinata a mettere in contatto rapidamente\
  \ delle famiglie europee, disposte ad accogliere dei rifugiati ucraini, con questi\
  \ ultimi. \nMaggiori dettagli anche qui: https://www.avvenire.it/economia/pagine/il-sito-che-trova-gratis-un-tetto-ai-rifugiati-ucraini-in-europa"
url: https://it.eu4ua.org/
address:
  mode: autocomplete
  address:
    place_id: 286311057
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: node
    osm_id: 25871341
    boundingbox:
    - '26'
    - '76'
    - '-15'
    - '35'
    lat: '51'
    lon: '10'
    display_name: Europa
    class: place
    type: continent
    importance: 0.9307067191883178
    address:
      place: Europa
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/73
