### ISSUE TITLE
Mamma con due bambini fuggita dall’Ucraina cerca casa e lavoro a Pavia e dintorni

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#301]
<pre><yamldata>
nameSurname: Shpirka Diana
phoneNumber: +39 340 3943816
email: mtroldy.gas@gmail.com
title: Cerca una casa per sè e due bambini, possibilmente a Pavia o dintorni. E' ospitata
  attualmente da un'amica in un monolocale. Cerca anche lavoro
recipients: ''
description: Il numero di telefono è dell'amica che li ospita, parla italiano. la
  mail di una volontaria che li sta aiutando, Maria Teresa Oldani
url: ''
location:
  mode: autocomplete
  address:
    place_id: 283772748
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 43483
    boundingbox:
    - '44.6799091'
    - '45.393838'
    - '8.4978518'
    - '9.5505475'
    lat: '45.036854649999995'
    lon: '9.137825082826026'
    display_name: Pavia, Lombardia, Italia
    class: boundary
    type: administrative
    importance: 0.7322019961097704
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      county: Pavia
      state: Lombardia
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
label: help
submit: true
Posizione: 45.036854649999995 9.137825082826026
</yamldata></pre>

**Comment by cristigalas** [comment]
Ha risolto attraverso amica di Anna Ghezzi.
