### ISSUE TITLE
Comune di Bari cerca interpreti volontari e mediatori culturali di lingua ucraina

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#327]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: false
  Legal: false
  translation: false
  job: true
  psychologicalSupport: false
  Children: false
  disability: false
  women: false
offerFromWho: Comune di Bari
title: Bari, Comune ricerca interpreti e mediatori
recipients: ''
description: 'Il Comune di Bari ha lanciato un avviso pubblico per la costituzione
  di: 1) short list di interpreti volontari di lingua ucraina per fini di solidarieta’
  2) short list di mediatori linguistico culturali di lingua ucraina per il superamento
  della barriera linguistica volta all’attivazione di tutti i servizi funzionali all’accoglienza
  ed all’inclusione dei profughi ucraini che stanno giungendo sul territorio cittadino.

  Scadenza: 24 aprile 2022'
url: https://www.comune.bari.it/-/2022-03-22-avviso-interpreti-e-mediatori-ucraina?fbclid=IwAR0waqAsGGB16inlSJPSw6dTLRjOVA_QlYQTJrmN85xM_WFtdoqukvVFUds
address:
  mode: autocomplete
  address:
    place_id: 285627565
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: node
    osm_id: 68528585
    boundingbox:
    - '40.9657843'
    - '41.2857843'
    - '16.7020293'
    - '17.0220293'
    lat: '41.1257843'
    lon: '16.8620293'
    display_name: Bari, Puglia, 70122, Italia
    class: place
    type: city
    importance: 0.7287183212532693
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_place_city.p.20.png
    address:
      city: Bari
      county: Bari
      state: Puglia
      postcode: '70122'
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduta, chiudo.
