### ISSUE TITLE
Supporto linguistico per i bambini ucraini

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#330]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: false
  Legal: false
  translation: true
  job: false
  psychologicalSupport: true
  Children: true
  disability: false
  women: false
offerFromWho: PASSAGGI e gruppo di Neuro e Psicomotricità dell'Età Evolutiva (TNPEE) .
title: Supporto linguistico per i bambini ucraini
recipients: Minori
description: Un opuscolo/schede di carattere linguistico per aiutare i bambini ucraini
  ad apprendere parole chiave per comunicare nell'immediato. Elaborato da Sara M.
  di Senza confini Tpee.
url: ''
address:
  mode: autocomplete
  address:
    place_id: 283780300
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 40123
    boundingbox:
    - '39.8448012'
    - '39.9090916'
    - '16.4778291'
    - '16.5773263'
    lat: '39.8701066'
    lon: '16.530667'
    display_name: Trebisacce, Cosenza, Calabria, 87075, Italia
    class: boundary
    type: administrative
    importance: 0.6169574919488509
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      village: Trebisacce
      county: Cosenza
      state: Calabria
      postcode: '87075'
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Non c'è link o altro riferimento per accedere o chiedere opuscolo.
