### ISSUE TITLE
A Bastia Umbra uova pasquali pro emergenza Ucraina

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#345]
<pre><yamldata>
title: L’associazione di accoglienza e solidarietà internazionale Orizzonti Assisi,
  supportata dal Cesvol Umbria e con il patrocinio del Comune di Bastia Umbra
description: 'BASTIA UMBRA – Iniziativa di solidarietà pro emergenza Ucraina
 L’associazione di accoglienza e solidarietà internazionale Orizzonti Assisi, supportata
  dal Cesvol Umbria e con il patrocinio del Comune di Bastia Umbra, promuove una raccolta
  fondi attraverso la proposta di acquisto solidale di uova di Pasqua, il cui ricavato
  sarà destinato all’ospitalità dei profughi ucraini.
Per prenotazioni delle uova al latte e al cioccolato fondente è possibile contattare
  i numeri 3389609785 /075 8018203.'
heading: ''
iban: ''
bicSwift: ''
ccPostal: ''
causal: ''
link: https://www.cesvolumbria.org/news/un-uovo-sorpresa-gioia-di-donare/
email: ''
location:
  mode: autocomplete
  address:
    place_id: 283842069
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 42302
    boundingbox:
    - '43.031678'
    - '43.0913888'
    - '12.4904338'
    - '12.5721251'
    lat: '43.0677554'
    lon: '12.5495816'
    display_name: Bastia Umbra, Perugia, Umbria, 06083, Italia
    class: boundary
    type: administrative
    importance: 0.6933899802161939
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      town: Bastia Umbra
      county: Perugia
      state: Umbria
      postcode: 06083
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
label: fundraising
submit: true
Posizione: 43.0677554 12.5495816
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduta, chiudi.
