### ISSUE TITLE
Terre des Hommes offre a Milano supporto a minori e famiglie rifugiate

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#352]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: false
  Legal: true
  translation: false
  job: false
  psychologicalSupport: true
  Children: true
  disability: false
  women: false
  education: false
offerFromWho: Terre des Hommes
title: Terre des Hommes offre a Milano supporto a minori e famiglie
recipients: ''
description: ''
url: https://www.facebook.com/groups/ukrainehelpit/permalink/466764085192545/
address:
  mode: autocomplete
  address:
    place_id: 170099285
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: way
    osm_id: 282060659
    boundingbox:
    - '45.506373'
    - '45.5065396'
    - '9.0976711'
    - '9.0977629'
    lat: '45.506373'
    lon: '9.0976711'
    display_name: Via Appennini, Gallaratese, Quartiere Gallaratese, Milano, Lombardia,
      20016, Italia
    class: highway
    type: tertiary
    importance: 0.4
    address:
      road: Via Appennini
      quarter: Gallaratese
      suburb: Quartiere Gallaratese
      city: Milano
      county: Milano
      state: Lombardia
      postcode: '20016'
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #361.
