### ISSUE TITLE
Supporto legale

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#356]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: false
  Legal: true
  translation: false
  job: false
  psychologicalSupport: false
  Children: false
  disability: false
  women: false
  education: false
offerFromWho: Avvocato di Strada
title: Supporto legale
recipients: profughi
description: "L'Organizzazione di volontariato \"Avvocato di strada\" mette a disposizione\
  \ per i profughi di guerra\n\n1. Task force di avvocati attività di tutela legale\
  \ presso alcune sedi locali*\n2. Mail dedicata (emergenza@avvocatodistrada.it) per\
  \ orientamento ai servizi sul territorio: \n3. Pagina web (https://tinyurl.com/ycn6coyw)\
  \ con info su protezione internazionale, protezione temporanea, accoglienza in fase\
  \ emergenziale, contatti e informazioni utili dai territori.\n\n*Sedi locali: https://www.avvocatodistrada.it/sedi-locali/\n\
  Ancona, Andria, Bari, Bologna, Bolzano, Brescia, Brindisi, Cagliari, Catania, Cerignola,\
  \ Cesena, Cremona, Cosenza, Ferrara, Firenze, Foggia, Forlì, Genova, Jesi, La Spezia,\
  \ Lecce, Lodi, Lucca, Macerata, Mantova, Matera, Milano, Modena, Monza, Napoli,\
  \ Padova, Palermo, Parma, Pavia, Pesaro, Perugia, Pescara, Piacenza, Pistoia, Ravenna,\
  \ Reggio Emilia, Rimini, Roma, Rovigo, Salerno, San Benedetto del Tronto, Siena,\
  \ Siracusa, Taranto, Torino, Trieste, Treviso, Venezia, Verona, Vicenza, Villacidro\
  \ Viterbo"
url: https://www.avvocatodistrada.it/faq-emergenza-ucraina-2022/
address:
  mode: autocomplete
  address:
    place_id: 283848615
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 43172
    boundingbox:
    - '44.421033'
    - '44.556094'
    - '11.2296206'
    - '11.4336079'
    lat: '44.4938203'
    lon: '11.3426327'
    display_name: Bologna, Emilia-Romagna, Italia
    class: boundary
    type: administrative
    importance: 0.7905771109268431
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      city: Bologna
      county: Bologna
      state: Emilia-Romagna
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente. Vedi #355.
