### ISSUE TITLE
Torino, sportelli sociali e punti informativi per stranieri

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#369]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: false
  Legal: true
  translation: false
  job: false
  psychologicalSupport: true
  Children: false
  disability: false
  women: true
  education: false
offerFromWho: Rete delle Case del quartiere
title: Torino - Sportelli sociali e punti informativi
recipients: popolazione straniera
description: "In tutte le Case del Quartiere sono presenti spazi di ascolto, accoglienza\
  \ e orientamento:\n- sportelli sociali,\n- punti informativi dedicati alla popolazione\
  \ straniera.\nSe hai bisogno di supporto nello svolgimento di pratiche burocratiche\
  \ o conosci qualcuno in difficoltà vieni nelle Case DelQuartiere o prendi un appuntamento\
  \ con i nostri operatori! \nQui orari e contatti dei servizi su > http://www.retecasedelquartiere.org/servizi.../accoglienza/"
url: http://www.retecasedelquartiere.org/servizi.../accoglienza/
address:
  mode: autocomplete
  address:
    place_id: 284787924
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 43992
    boundingbox:
    - '45.0067924'
    - '45.1402175'
    - '7.5778348'
    - '7.7733388'
    lat: '45.0677551'
    lon: '7.6824892'
    display_name: Torino, Piemonte, Italia
    class: boundary
    type: administrative
    importance: 0.8068062387577691
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      city: Torino
      county: Torino
      state: Piemonte
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #392.
