### ISSUE TITLE
TELEFONO VERDE MALATTIE RARE   800 89 69 49

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#380]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: true
  Legal: false
  translation: false
  job: false
  psychologicalSupport: false
  Children: false
  disability: false
  women: false
  education: false
offerFromWho: CNMR - Centro Nazionale Malattie Rare dell’Istituto Superiore di Sanità
title: TELEFONO VERDE MALATTIE RARE   800 89 69 49
recipients: ''
description: 'Il servizio gestito dal CNMR - Centro Nazionale Malattie Rare dell’Istituto
  Superiore di Sanità risponde al numero 800 89 69 49, ha copertura nazionale ed è
  gratuito da telefono fisso e da cellulare.
  Il numero è attivo dal lunedì al venerdì dalle ore 9:00 alle ore 13:00.
Per i residenti all’estero, che non possono utilizzare il numero verde, è attiva
  una casella e-mail: tvmr@iss.it
  Per favorire l’accessibilità delle persone sorde al servizio di counselling telefonico,
  grazie all’Accordo di collaborazione scientifica tra l’Istituto Superiore di Sanità
  e il Dipartimento di Studi Linguistici e Culturali Comparati dell’Università Ca’
  Foscari di Venezia, è stata aperta l’e-mail: tvmrlis@iss.it

  Attraverso il Telefono Verde è possibile accedere ai Coordinamento Regionali per
  le malattie rare per individuare velocemente la disponibilità di posti letto/ricovero
  nelle strutture ospedaliere regionali, etc. etc.

  Inoltre sempre attraverso il Telefono Verde è anche possibile un accedere a UNIAMO,
  la Federazione Italiana di Associazioni di pazienti di malattie rare che può contribuire
  alla realizzazione delle azioni proposte mediante il collegamento con singole Associazioni
  nazionale di malati rari (email: ucraina@uniamo.org )'
url: ''
address:
  mode: autocomplete
  address: {}
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Qui non è chiaro cosa si offra a chi sta o fugge dall’Ucraina. Pare un servizio per tutti, anche se in fondo si accenna ad una mail dedicata. E comunque non c’è link di rimando e comunque andando sul sito di questo Telefono Verde si ritrova lo stesso testo. 
Cosa ne dite @favoeva @patriziacar @luciroma?

**Comment by cristigalas** [comment]
Vedi qui https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/454
