### ISSUE TITLE
FAQ e orientamento per tutela legale profughi a cura di ‘Avvocati di Strada’

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#406]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: false
  Legal: true
  translation: false
  job: false
  psychologicalSupport: false
  Children: false
  disability: false
  women: false
  education: false
offerFromWho: Avvocato di strada
title: FAQ e orientamento per tutela legale profughi
recipients: ''
description: 'Avvocato di strada ha attivato una mail per richieste di informazioni
  a carattere generale, orientamento ai servizi sul territorio o altre necessità che
  riguardano la guerra in Ucraina: emergenza@avvocatodistrada.it.

  Sulla base delle domande fatte più comunemente, e sulle informazioni che abbiamo
  raccolto in queste settimane, hanno creato queste FAQ per fornire le informazioni
  generali per capire gli istituti giuridici applicabili alla situazione e raccogliere
  i contatti utili su tutto il territorio nazionale e che mettiamo a disposizione
  di istituzioni, associazioni, operatori e semplici cittadini.'
url: https://www.avvocatodistrada.it/faq-emergenza-ucraina-2022/
address:
  mode: autocomplete
  address:
    place_id: 284007015
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 365331
    boundingbox:
    - '35.2889616'
    - '47.0921462'
    - '6.6272658'
    - '18.7844746'
    lat: '42.6384261'
    lon: '12.674297'
    display_name: Italia
    class: boundary
    type: administrative
    importance: 0.9831019031440554
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by favoeva** [comment]
Doppia

**Comment by cristigalas** [comment]
Chiudiamo.
