### ISSUE TITLE
Il comune di Cento raccoglie disponibilità per organizzare iniziative per l'integrazione di bambine 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#409]
<pre><yamldata>
nameSurname: Comune di Cento
phoneNumber: ''
email: facciamorete@comune.cento.fe.it
title: Il comune di Cento raccoglie disponibilità per organizzare iniziative per l'integrazione
  di bambine e bambini
recipients: ''
description: 'Il Comune di Cento vuole o di favorire l''integrazione dei bambini accolti
  sul territorio raccogliendo la disponibilità ad organizzare o condividere le proprie
  iniziative. In questa fase il Comune è anche in cerca di un aiuto per comprendere
  la lingua e diffondere meglio queste attività.

  Si possono segnalare idee e disponibilità a facciamorete@comune.cento.fe.it'
url: https://www.comune.cento.fe.it/aree-tematiche/volontariato-e-associazionismo/facciamo-rete-coordinamento-solidale-lintegrazione
location:
  mode: autocomplete
  address:
    place_id: 283662905
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 43506
    boundingbox:
    - '44.705628'
    - '44.8381841'
    - '11.2461129'
    - '11.3880712'
    lat: '44.7274395'
    lon: '11.2903029'
    display_name: Cento, Unione Alto Ferrarese, Ferrara, Emilia-Romagna, Italia
    class: boundary
    type: administrative
    importance: 0.5819924514729962
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      town: Cento
      municipality: Unione Alto Ferrarese
      county: Ferrara
      state: Emilia-Romagna
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
label: help
submit: true
Posizione: 44.7274395 11.2903029
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
