### ISSUE TITLE
Il comune di Cento organizza attività per minori

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#411]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: false
  Legal: false
  translation: false
  job: false
  psychologicalSupport: false
  Children: true
  disability: false
  women: false
  education: false
offerFromWho: Comune di Cento
title: Il comune di Cento organizza attività per minori
recipients: ''
description: 'L''Assessorato al Volontariato del Comune di Cento promuove l''organizzazione
  e la segnalazione di iniziative sportive, culturali o di volontariato per l''integrazione
  dei minori profughi accolti nel nostro territorio.

  Le associazioni che vorranno organizzare qualche iniziativa o segnalare iniziative
  esistenti utili allo scopo possono scrivere a: facciamorete@comune.cento.fe.it

  Il Comune è anche alla ricerca di volontari bilingue per realizzare con successo
  questo evento!: se parli l''italiano e l''ucraino e ti va di donare un pò del tuo
  tempo per aiutarci durante queste iniziative, contattaci a: facciamorete@comune.cento.fe.it

  Le informazioni reperite saranno finalizzate alla creazione di un calendario coordinato
  e alla segnalazione e promozione.'
url: https://www.comune.cento.fe.it/aree-tematiche/volontariato-e-associazionismo/facciamo-rete-coordinamento-solidale-lintegrazione
address:
  mode: autocomplete
  address:
    place_id: 283662905
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 43506
    boundingbox:
    - '44.705628'
    - '44.8381841'
    - '11.2461129'
    - '11.3880712'
    lat: '44.7274395'
    lon: '11.2903029'
    display_name: Cento, Unione Alto Ferrarese, Ferrara, Emilia-Romagna, Italia
    class: boundary
    type: administrative
    importance: 0.5819924514729962
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      town: Cento
      municipality: Unione Alto Ferrarese
      county: Ferrara
      state: Emilia-Romagna
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
