### ISSUE TITLE
Trasporti gratuiti per i cittadini ucraini in Italia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#445]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: true
  healthcare: false
  Legal: false
  translation: false
  job: false
  psychologicalSupport: false
  Children: false
  disability: false
  women: false
  education: false
offerFromWho: Governo Italiano
title: Trasporti gratuiti per i cittadini ucraini in Italia
recipients: ''
description: L’ordinanza di protezione civile prevede che i cittadini provenienti
  dall’Ucraina possano viaggiare gratuitamente sul nostro territorio, entro 5 giorni
  massimo dall’ingresso in Italia, per raggiungere il primo luogo di destinazione
  o di accoglienza. Il provvedimento comprende la gratuità del trasporto sui treni
  della società Trenitalia (Gruppo FS) che effettuano servizio di Intercity, Eurocity
  e Regionali, sui servizi marittimi e sulla rete autostradale.
url: https://www.governo.it/it/articolo/emergenza-ucraina-trasporti-gratuiti-i-cittadini-ucraini-italia/19388
address:
  mode: autocomplete
  address: {}
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #133.
