### ISSUE TITLE
Bando per misure straordinarie in denaro e servizi a favore di studenti ucraini

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#446]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: true
  transport: false
  healthcare: false
  Legal: false
  translation: false
  job: false
  psychologicalSupport: false
  Children: false
  disability: false
  women: false
  education: true
offerFromWho: Regione Emilia Romagna, ER.GO – Azienda Regionale per il Diritto agli
  Studi Superiori dell’Emilia
title: Bando per misure straordinarie in denaro e servizi a favore di studenti ucraini
recipients: Studenti ucraini
description: La Regione Emilia Romagna, ER.GO – Azienda Regionale per il Diritto agli
  Studi Superiori dell’Emilia - Romagna e le Università di Bologna, di Ferrara, di
  Modena e Reggio Emilia, di Parma, l’Università Cattolica del Sacro Cuore di Milano
  sede di Piacenza e il Politecnico di Milano sede di Piacenza mettono a disposizione
  misure straordinarie in denaro e servizi a favore di studenti ucraini.
url: https://www.er-go.it/index.php?id=5866&tx_ttnews%5Btt_news%5D=3006&tx_ttnews%5BbackPid%5D=5886&cHash=6715020f0e7e3dae32de467b77acc1e0
address:
  mode: autocomplete
  address:
    place_id: 284957631
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 42611
    boundingbox:
    - '43.7318997'
    - '45.1395001'
    - '9.1979117'
    - '12.7559006'
    lat: '44.525696'
    lon: '11.039437'
    display_name: Emilia-Romagna, Italia
    class: boundary
    type: administrative
    importance: 0.8658836089993998
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      state: Emilia-Romagna
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #363
