### ISSUE TITLE
Comune di Verona organizza un corso gratuito di italiano per profughi ucraini

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#458]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: false
  Legal: false
  translation: true
  job: false
  psychologicalSupport: false
  Children: false
  disability: false
  women: false
  education: false
offerFromWho: Comune di Verona
title: Corso di italiano per ucraini
recipients: ''
description: 'Il Comune di Verona organizza, insieme al Centro provinciale Istruzione Adulti, corso di italiano per gli ucraini ospitati a Verona: lezioni gratuite al fine di favorire l’integrazione di coloro che sono scappati dalla guerra e hanno trovato accoglienza in città. La raccolta delle adesioni è già aperta, una ventina i posti a disposizione. Le lezioni avranno una durata di 100 ore e si terranno da metà aprile a metà giugno, la mattina dalle 9 alle 12.30, in zona Stadio. Le domande possono essere inviate entro lunedì 11 aprile al Servizio Promozione Lavoro del Comune, inviando una mail a lavoro@comune.verona.it 
Ulteriori info al link.'
url: https://redir.ownpage.fr/newsletter/09a3f59d5c724ed6/eyJzIjoiN2VjOTBjMDkiLCJhciI6IjYyNDgyZTAwYWEyY2Y0MDAwNzM1ZDA5OSIsInUiOiJkYTQ5MTk2ZWIxYzhkNzkyMTUxMDJhMWEyNTc1YjdiYiIsInVyIjoiaHR0cHM6Ly93d3cubGFyZW5hLml0L3RlcnJpdG9yaS9jaXR0YS9pbC1jb211bmUtYXZ2aWEtY29yc28tZ3JhdHVpdG8tZGktaXRhbGlhbm8tcGVyLWdsaS11Y3JhaW5pLWFwZXJ0ZS1sZS1pc2NyaXppb25pLTEuOTMyNTkwNj9fb3BlPWV5Sm5kV2xrSWpvaVpHRTBPVEU1Tm1WaU1XTTRaRGM1TWpFMU1UQXlZVEZoTWpVM05XSTNZbUlpZlElM0QlM0QiLCJnIjoiMTk0NjY5IiwicCI6IjIwIn0=
address:
  mode: autocomplete
  address:
    place_id: 284390209
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 44830
    boundingbox:
    - '45.3494402'
    - '45.5418375'
    - '10.8768512'
    - '11.1239'
    lat: '45.445596300000005'
    lon: '10.98133966814804'
    display_name: Verona, Veneto, Italia
    class: boundary
    type: administrative
    importance: 0.7561573888828526
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      city: Verona
      county: Verona
      state: Veneto
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/489
