### ISSUE TITLE
Fairbnb: piattaforma gratuita per rifugiati e persone in difficoltà abitativa

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#464]
<pre><yamldata>
title: 'Fairbnb: piattaforma gratuita per rifugiati e persone in difficoltà abitativa'
description: Fairbnb.coop, cooperativa che opera nel campo del turismo responsabile
  a livello internazionale, ed è supportata da Banca Etica, mette a disposizione –
  e per ora visibile solo ai gestori – una versione gratuita della propria piattaforma
  Web, privata ovviamente di tutti gli elementi di tipo commerciale e destinata a
  consentire l’incrocio tra la domanda e l’offerta di rifugi per persone in difficoltà.
  Tramite una sorta di chiamata collettiva online, Fairbnb offre l’utilizzo dell’infrastruttura
  agli operatori umanitari, alle varie organizzazioni impegnate nell’accoglienza e,
  più in generale, nella presa in carico delle situazioni di disagio abitativo innanzitutto
  in Italia e nei diversi Paesi dove la cooperativa ha referenti.
link: https://www.bancaetica.it/fairbnb-rifugiati-e-difficolta-abitativa/?fbclid=IwAR0UqQ1kXIq4K37egDg7LfTinQmNbx8VIThnMhpt4ykTzoy59V2nwU2uv4o
location:
  mode: autocomplete
  address: {}
label: news
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #437
