### ISSUE TITLE
Mrs

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#473]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: true
  healthcare: false
  Legal: true
  translation: false
  job: true
  psychologicalSupport: true
  Children: true
  disability: false
  women: false
  education: false
offerFromWho: Alla
title: Mrs
recipients: Ukraine
description: ''
url: ''
address:
  mode: autocomplete
  address:
    place_id: 284963980
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 41509
    boundingbox:
    - '41.7246509'
    - '41.7831368'
    - '12.6825095'
    - '12.8013688'
    lat: '41.7607608'
    lon: '12.7096141'
    display_name: Rocca di Papa, Roma Capitale, Лацио, Италия
    class: boundary
    type: administrative
    importance: 0.8075486945575742
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      town: Rocca di Papa
      county: Roma Capitale
      state: Лацио
      country: Италия
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Incompleta.
