### ISSUE TITLE
Attrice ed insegnate in ambito teatrale e linguistico

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#497]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: false
  Legal: false
  translation: true
  job: false
  psychologicalSupport: false
  Children: true
  disability: false
  women: false
  education: false
offerFromWho: Cittadina
title: Attrice ed insegnate in ambito teatrale e linguistico
recipients: Bambini e minotri
description: 'Assistenza a bambini e minori. Laboratori teatrali per ritrovare in
  gruppo la relazione e il

  Gioco in lingua italiana e inglese'
url: ''
address:
  mode: manual
  address:
    address1: Roma
    address2: Via pietro borsieri 20
    city: Roma
    state: Italia
    country: Italia
    zip: 00195
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Questa non l'accetterei, non lascia un recapito né un link per verificare e non spiega dove eventualmente svolge questi laboratori e se sono gratuiti.
