### ISSUE TITLE
Da Mykolaiv famiglia con bambino disabile chiede di lasciare la città e raggiungere l’Italia

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#498]
<pre><yamldata>
nameSurname: Khrystyna Brutska
phoneNumber: '+380930030940'
email: brutska.kris@gmail.com
title: Please help
recipients: Volunteers
description: "Hello!\nMy name is Christina Brutska. I'm from Mykolaiv city, Ukraine.\
  \ \nMy younger brother Kostya is disabled. He is 4.5 years old, has Cerebral Palsy,\
  \ and needs a rehabilitation course, which we cannot get in the conditions of war\
  \ in our country. On top of that, Mykolaiv is constantly under fire now, and he\
  \ with my mother are in danger.\n\nWe want to ask, Can you help? We want to come\
  \ to Italy in a few days.\nThank you for your consideration. We are waiting for\
  \ your response."
url: ''
location:
  mode: autocomplete
  address:
    place_id: 285485289
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 11622860
    boundingbox:
    - '46.818256'
    - '47.0475231'
    - '31.8804797'
    - '32.1351928'
    lat: '46.932879549999996'
    lon: '32.00211658147113'
    display_name: Николаев, Миколаївська міська громада, Николаевский район, Николаевская
      область, 54000-54490, Украина
    class: place
    type: city
    importance: 0.5651907576372511
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_place_city.p.20.png
    address:
      city: Николаев
      municipality: Миколаївська міська громада
      district: Николаевский район
      state: Николаевская область
      postcode: 54000-54490
      country: Украина
      country_code: ua
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
label: help
submit: true
Posizione: 46.932879549999996 32.00211658147113
</yamldata></pre>

**Comment by cristigalas** [comment]
Con @luciroma e @patriziacar stiamo facendo alcune verifiche di contatti utili e comunque le scriviamo via mail per chiederle più info.

**Comment by cristigalas** [comment]
Risolta. La ragazza ha trovato trasporto per Polonia e poi Roma. Vedi [chat Telegram](https://t.me/ukraineinfohelp/2705).
