### ISSUE TITLE
Жилье на 4 человек и питание

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#529]
<pre><yamldata>
nameSurname: Влад Ковальов
phoneNumber: '+380636055440'
email: vladkovalov586@gmail.com
title: Жилье на 4 человек и питание
recipients: ''
description: ''
url: ''
location:
  mode: autocomplete
  address: {}
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
label: help
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/527
