### ISSUE TITLE
Scuola d'italiano free

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#535]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: false
  Legal: false
  translation: false
  job: false
  psychologicalSupport: false
  Children: false
  disability: false
  women: false
  education: true
offerFromWho: MOVIMENTO COOPERAZIONE ITALIANA, MOCI
title: Scuola d'italiano free
recipients: ''
description: 'La scuola di italiano è gratuita e offre 2 livelli di preparazione :Italiano
  A1 e italianoA2.

  Le lezioni si svolgono tutti i

  MARTEDÌ E GIOVEDÌ ORE 17.00 - 19.00.'
url: ''
address:
  mode: autocomplete
  address: {}
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Non dice dove si svolge, non c’è nessun rimando con link e coordinate. Sul loro sito e pagina Fb non ho trovano nessuna notizia su questa scuola. Non accetto.
