### ISSUE TITLE
Bus e tramvia gratis per i profughi ucraini

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#536]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: true
  healthcare: false
  Legal: false
  translation: false
  job: false
  psychologicalSupport: false
  Children: false
  disability: false
  women: false
  education: false
offerFromWho: Regione Toscana e Comune di Firenze
title: Bus e tramvia gratis per i profughi ucraini
recipients: ''
description: Profughi ucraini potranno utilizzare gratuitamente il trasporto pubblico
  su gomma della Toscana e la tramvia di Firenze.
url: https://www.firenzetoday.it/cronaca/autobus-tram-profughi-ucraini.html
address:
  mode: autocomplete
  address:
    place_id: 283877734
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 42472
    boundingbox:
    - '43.4515008'
    - '44.2398961'
    - '10.7111211'
    - '11.7529365'
    lat: '43.84571535'
    lon: '11.374009954589173'
    display_name: Città metropolitana di Firenze, Toscana, Italia
    class: boundary
    type: administrative
    importance: 0.5714395551097098
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      county: Città metropolitana di Firenze
      state: Toscana
      ISO3166-2-lvl4: IT-52
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
C’è già, vedi #515.
