### ISSUE TITLE
Consolato ucraino a Genova - Contatti utili

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#560]
<pre><yamldata>
title: Consolato ucraino a Genova - Contatti utili
phoneNumber: +39 06 841 26 305 (Embassy in Rome)
email: emb_it@mfa.gov.ua
aim: 'Il consolato Ucraina a Genova è guidato da Vacant - Console Onorario del Ucraina
  in Italia e si può parlare con il consolato (+39) (06) 841 26 305 (Embassy in Rome)
  ou inviare un email: emb_it@mfa.gov.ua'
url: italy.mfa.gov.ua/it
address:
  mode: autocomplete
  address: {}
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: useful contact
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente vedi https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/554
