### ISSUE TITLE
Elenco delle chiese cattoliche ucraine nel nord Italia con info e contatti

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#578]
<pre><yamldata>
title: Elenco delle chiese ucraine nel nord Italia con info e contatti
phoneNumber: ''
email: ''
aim: Sul sito della Chiesa greco-cattolica ucraina è disponibile l'elenco delle chiese
  ucraine in tutta Italia. Al momento però è consultabile sono l'elenco delle chiese
  ucraine nel nord Italia. Gli altri due elenchi per il centro e sud d'Italia non
  sono accessibili perché i link risultano corrotti.
url: http://www.chiesaucraina.it/index.php/it/ugcc-in-italia/parocchie-e-comunit%C3%A0/italia-del-nord.html#
address:
  mode: autocomplete
  address: {}
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: useful contact
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Piu completa questa https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/579
Chiudo.
