### ISSUE TITLE
Accoglienza diffusa dei rifugiati ucraini, bando del Dipartimento Nazionale Protezione Civile (scadenza 22 aprile)

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#591]
<pre><yamldata>
title: Accoglienza diffusa dei rifugiati ucraini, bando del Dipartimento della protezione
  civile (scadenza 22 aprile)
description: 'Offrire misure di accoglienza diffusa e di accompagnamento per l’integrazione
  e l’autonomia alle persone provenienti dall’Ucraina.

  Questo l’oggetto dell’avviso pubblicato oggi dal Dipartimento sulla base dell’art.
  1 dell’Ocdpc n. 881 del 29 marzo 2022, con l’obiettivo di acquisire le manifestazioni
  di interesse di rilievo nazionale da parte degli enti individuati dall’art. 31 del
  decreto-legge n. 21 del 21 marzo 2022.

  I soggetti interessati potranno manifestare il proprio interesse entro le ore 18
  del 22 aprile 2022 utilizzando la piattaforma https://avvisiebandi-emergenzaucraina.protezionecivile.gov.it

  Per ulteriori info vedi link.'
link: https://www.protezionecivile.gov.it/it/notizia/emergenza-ucraina-al-la-raccolta-delle-manifestazioni-dinteresse-laccoglienza-diffusa-delle-persone-provenienti-dallucraina-0
location:
  mode: autocomplete
  address:
    place_id: 59550508
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: node
    osm_id: 5462543512
    boundingbox:
    - '41.9039326'
    - '41.9040326'
    - '12.4718709'
    - '12.4719709'
    lat: '41.9039826'
    lon: '12.4719209'
    display_name: Dipartimento della Protezione Civile, 11, Via Ulpiano, Prati, Municipio
      Roma I, Roma, Roma Capitale, Lazio, 00186, Italia
    class: office
    type: government
    importance: 0.42099999999999993
    address:
      office: Dipartimento della Protezione Civile
      house_number: '11'
      road: Via Ulpiano
      quarter: Prati
      suburb: Municipio Roma I
      city: Roma
      county: Roma Capitale
      state: Lazio
      postcode: 00186
      country: Italia
      country_code: it
label: news
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
submit: true
Posizione: 41.9039826 12.4719209
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduta, chiudo.
