### ISSUE TITLE
Offro lavoro come SARTA/O  nella mia sartoria artigianale  3335008426

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#597]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: false
  Legal: false
  translation: false
  job: true
  psychologicalSupport: false
  Children: false
  disability: false
  women: false
  education: false
offerFromWho: Sartoria del Duomo
title: Offro lavoro come SARTA/O  nella mia sartoria artigianale  3335008426
recipients: Sarta/o professionista
description: ''
url: ''
address:
  mode: manual
  address:
    address1: 'Capua '
    address2: ''
    city: Capua
    state: 'Italia '
    country: ''
    zip: '81043'
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/507
