### ISSUE TITLE
A Prato e provincia, presso vari circoli Arci, raccolta di beni alimentari e biancheria per emergenza Ucraina 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#599]
<pre><yamldata>
servicetypes:
  materialGoods: true
  hospitality: false
  transport: false
  healthcare: false
  Legal: false
  translation: false
  job: false
  psychologicalSupport: false
  Children: false
  disability: false
  women: false
  education: false
offerFromWho: Arci Prato
title: A Prato e provincia, presso vari circoli Arci, raccolta di beni alimentari,
  cibo e biancheria per emergenza Ucraina
recipients: ''
description: 'Nei circoli Arci di Cafaggio, Paperino, Poggio a Caiano, Carmignano,
  Galciana, Maliseti, Viaccia, Vaiano, Figline, La Macine, Mezzana e presso il Circolo
  Orsetti – Spazio AUT nel centro storico, è attiva fino al 15 aprile una raccolta
  di beni di prima necessità per la popolazione ucraina. Sono richiesti: cibo in scatola
  e/o a lunga conservazione (pasta, riso, latte, pane in sacchetto, dryfood, acqua
  ecc.), biancheria intima nuova per ragazze e ragazzi tra i 5 e i 20 anni.'
url: https://www.arciprato.it/2022/04/08/raccolta-generi-di-prima-necessita-per-lucraina/
address:
  mode: autocomplete
  address:
    place_id: 144268250
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: way
    osm_id: 175300490
    boundingbox:
    - '43.84753'
    - '43.8476698'
    - '11.0747686'
    - '11.074994'
    lat: '43.8475568'
    lon: '11.0748914'
    display_name: Via Roma, Fontanelle, Prato, Toscana, 59016, Italia
    class: highway
    type: secondary
    importance: 0.41000000000000003
    address:
      road: Via Roma
      suburb: Fontanelle
      city: Prato
      county: Prato
      state: Toscana
      ISO3166-2-lvl4: IT-52
      postcode: '59016'
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduta, chiudo.
