### ISSUE TITLE
Pubblicato l'avviso per raccogliere le disponibilità del terzo settore all'accoglienza diffusa dei rifugiati ucraini 

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#609]
<pre><yamldata>
title: Pubblicato l'avviso per raccogliere le disponibilità del terzo settore per
  l'accoglienza diffusa dei rifugiati ucraini
description: 'Pubblicato l''avviso per l''acquisizione di manifestazioni d''interesse
  per lo svolgimento di attività di accoglienza diffusa nel territorio nazionale a
  beneficio delle persone provenienti dall''Ucraina in fuga dagli eventi bellici in
  atto e l''accompagnamento per l’integrazione e l’autonomia alle persone provenienti
  dall’Ucraina.

  Questo l’oggetto dell’avviso pubblicato oggi dal Dipartimento sulla base dell’art.
  1 dell’Ocdpc n. 881 del 29 marzo 2022, con l’obiettivo di acquisire le manifestazioni
  di interesse di rilievo nazionale da parte degli enti individuati dall’art. 31 del
  decreto-legge n. 21 del 21 marzo 2022.

  I soggetti interessati potranno manifestare il proprio interesse entro le ore 18:00
  del 22 aprile 2022 utilizzando la piattaforma: https://avvisiebandi-emergenzaucraina.protezionecivile.gov.it.'
link: https://www.lavoro.gov.it/notizie/Pagine/Emergenza-Ucraina-al-via-la-raccolta-delle-manifestazioni-d-interesse-per-l-accoglienza-diffusa-delle-persone-provenienti.aspx
location:
  mode: autocomplete
  address: {}
label: news
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente.
