### ISSUE TITLE
Raccolta medicinali e materiali sanitari nelle farmacie di Roma   e provincia - dal 9 al 16 marzo

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#64]
<pre><yamldata>
type: healthcare
offerFromWho: Federfarma Roma
title: Farmacisti per l'Ucraina
recipients: ''
description: Raccolta medicinali e materiali sanitari in tutte le farmacie di Roma
  e provincia - dal 9 al 16 marzo
url: 'https://twitter.com/ukraineinfohelp/status/1501526286585499649?t=gG4S2XxlCPzIjVTQO5XYVQ&s=19'
address:
  mode: autocomplete
  address:
    place_id: 283767136
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 41485
    boundingbox:
    - '41.6556417'
    - '42.1410285'
    - '12.2344669'
    - '12.8557603'
    lat: '41.8933203'
    lon: '12.4829321'
    display_name: Roma, Roma Capitale, Lazio, Italia
    class: boundary
    type: administrative
    importance: 0.8996107180689524
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      city: Roma
      county: Roma Capitale
      state: Lazio
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Scaduta. Chiudo.
