### ISSUE TITLE
Call Center regionale con informazioni per i rifugiati ucraini in Piemonte

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#705]
<pre><yamldata>
title: Call Center regionale con informazioni per i rifugiati ucraini in Piemonte
phoneNumber: '011.4326700'
email: accoglienza.ucraina@regione.piemonte.it
aim: 'E'' attivo da martedì 22 marzo il numero del Call Center regionale dedicato
  alle informazioni per i rifugiati ucraini in Piemonte, realizzato grazie alla collaborazione
  tra Protezione Civile, Consolato Onorario di Ucraina a Torino e la Onlus Danish
  Refugee Council Italia. Il numero è 011.4326700 ed è attivo dal lunedì al sabato,
  dalle 8.00 alle 20.00: otto operatori di madrelingua ucraina rispondono alle richieste
  di informazioni e approfondimenti da parte dei profughi e delle famiglie che li
  accolgono.'
url: https://www.regione.piemonte.it/web/temi/diritti-politiche-sociali/piemonte-per-lucraina#
address:
  mode: autocomplete
  address:
    place_id: 284787924
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 43992
    boundingbox:
    - '45.0067924'
    - '45.1402175'
    - '7.5778348'
    - '7.7733388'
    lat: '45.0677551'
    lon: '7.6824892'
    display_name: Torino, Piemonte, Italia
    class: boundary
    type: administrative
    importance: 0.8068062387577691
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      city: Torino
      county: Torino
      state: Piemonte
      ISO3166-2-lvl4: IT-21
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: useful contact
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi https://ukrainehelp.emergenzehack.info/issues/685/
