### ISSUE TITLE
Numero nazionale di pubblica utilità

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#706]
<pre><yamldata>
title: Numero nazionale di pubblica utilità
phoneNumber: '1500'
email: ''
aim: Il numero nazionale di pubblica utilità 1500 fornisce informazioni su assistenza
  sanitaria, green pass, Covid-19 agli stranieri in arrivo dall'Ucraina. Il servizio
  di risposta è attivo anche in lingua russa e ucraina dalle ore 8 alle 20, tutti
  i giorni.
url: https://www.regione.piemonte.it/web/temi/diritti-politiche-sociali/piemonte-per-lucraina#
address:
  mode: autocomplete
  address:
    place_id: 284007015
    licence: Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    osm_type: relation
    osm_id: 365331
    boundingbox:
    - '35.2889616'
    - '47.0921462'
    - '6.6272658'
    - '18.7844746'
    lat: '42.6384261'
    lon: '12.674297'
    display_name: Italia
    class: boundary
    type: administrative
    importance: 0.9931019031440554
    icon: https://nominatim.openstreetmap.org/ui/mapicons//poi_boundary_administrative.p.20.png
    address:
      country: Italia
      country_code: it
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: useful contact
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente https://github.com/emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni/issues/681
