### ISSUE TITLE
Ambulatorio Nessuno Escluso ad Alessandria

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#713]
<pre><yamldata>
servicetypes:
  materialGoods: false
  hospitality: false
  transport: false
  healthcare: true
  Legal: false
  translation: false
  job: false
  psychologicalSupport: false
  Children: false
  disability: false
  women: false
  education: false
offerFromWho: Caritas Alessandria
title: Ambulatorio Nessuno Escluso ad Alessandria
recipients: persone non residenti, senza fissa dimora e stranieri richiedenti o titolari
  di protezione internazionale o comunque temporaneamente presenti.
description: L’ambulatorio è gestito dall’Associazione Nessuno Escluso – ambulatorio
  medico onlus, sotto la Direzione del dott. Alberto Prete ed in coordinamento con
  il Centro di Ascolto, ed offre prestazioni gratuite di Medicina generale e specialistica,
  di Ginecologia e di Odontoiatria. Si rivolge primariamente a tutte quelle persone,
  uomini e donne, che seppur presenti sul territorio comunale non hanno accesso al
  medico di base poiché non residenti, senza fissa dimora e stranieri richiedenti
  o titolari di protezione internazionale o comunque temporaneamente presenti.
url: http://caritas.diocesialessandria.it/servizi-caritas/ambulatorio-nessuno-escluso/?fbclid=IwAR08e4bhaoqTTww13iF2Np-MZxFnzm8i5n9WRaqDLLwwgusoKe_61wr5FHg
address:
  mode: manual
  address:
    address1: via delle orfanelle 25
    address2: ''
    city: Alessandria
    state: italia
    country: italia
    zip: ''
iConfirmToHaveReadAndAcceptedInformativeToThreatPersonalData: true
label: services
submit: true
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente vedi #709
