### ISSUE TITLE
L'Associazione ANCI Umbria Prociv lancia una raccolta fondi per la popolazione della regione di Odessa

### ISSUE THREAD

**Issue by ehack-italy** [emergenzeHack/ukrainehelp.emergenzehack.info_segnalazioni#784]
<pre><yamldata>
title: ANCI Umbria Prociv
description: ANCI Umbria ProCiv si mobilita in risposta all'appello del Sindaco di Odessa, Gennadiy Trukhanov, lanciando una raccolta fondi per aiutare la popolazione ucraina della Regione di Odessa.
heading: ''
iban: ''
bicSwift: ''
ccPostal: ''
causal: ''
link: https://www.gofundme.com/f/aiuti-per-odessa?utm_medium=referral&utm_source=unknown&utm_campaign=comms_gfm+aiuti-per-odessa
email: ''
location:
  mode: autocomplete
  address: {}
iConfirmToHaveReadAndAcceptedPrivacyInformativeToThreatPersonalData: true
label: fundraising
submit: true
</yamldata></pre>

**Comment by claudiamazzantiact** [comment]
Chiusa perchè già presente #785
